// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Basket struct {
	ID     uuid.UUID     `db:"id"`
	UserID uuid.NullUUID `db:"user_id"`
}

type BasketProduct struct {
	ID        uuid.UUID     `db:"id"`
	BasketID  uuid.UUID     `db:"basket_id"`
	ProductID uuid.UUID     `db:"product_id"`
	Quantity  sql.NullInt32 `db:"quantity"`
}
