// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Seller struct {
	ID       uuid.UUID      `db:"id"`
	Name     string         `db:"name"`
	Email    string         `db:"email"`
	Password sql.NullString `db:"password"`
}
