// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"github.com/google/uuid"
)

type Product struct {
	ID       uuid.UUID     `db:"id"`
	Name     string        `db:"name"`
	Price    float64       `db:"price"`
	Rating   float64       `db:"rating"`
	BrandID  uuid.NullUUID `db:"brand_id"`
	SellerID uuid.UUID     `db:"seller_id"`
	Amount   int32         `db:"amount"`
}

type ProductImage struct {
	ID        uuid.UUID `db:"id"`
	ProductID uuid.UUID `db:"product_id"`
	File      string    `db:"file"`
}

type ProductProperty struct {
	ID        uuid.UUID `db:"id"`
	ProductID uuid.UUID `db:"product_id"`
	Name      string    `db:"name"`
	Value     string    `db:"value"`
}

type ProductsCategory struct {
	ProductsID   uuid.UUID `db:"products_id"`
	CategoriesID uuid.UUID `db:"categories_id"`
}
